services:
  database:
    container_name: database_wenlock
    image: postgres:16-alpine
    env_file: .env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend_wenlock
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
  frontend:
    container_name: frontend_wenlock
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgdata: